# Generated by Django 5.0.6 on 2024-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(help_text='Описание для торта', max_length=2000),
        ),
    ]
