# Generated by Django 5.0.6 on 2024-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cake_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость торта', max_digits=10),
        ),
    ]
